name: Testpbg
favicon: null
layout_spectrum: 0.44689632672816515
typography_spectrum: 0.48291237908415496
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.9930714936926961
  lightness: 0.9550833173561841
  saturation: 0.3317957930266857
  rhythmicContrast: 0.3843528227880597
purpose: []
